
DC=-sudo docker-compose
DCC=$(DC) exec app bash -c

_help:
	@echo Available tasks:
	@grep '^[^_#\\$$[:space:]][^=/[:space:]]*:' Makefile | cut -d: -f1 | xargs -n1 echo ' make'

shell:
	$(DCC) bash

sandbox:
	$(DCC) 'bin/rails console --sandbox'

console:
	$(DCC) 'bin/rails console'

webshell:
	$(DC) exec web bash

dbshell:
	$(DC) exec db bash

log:
	$(DC) logs

logf:
	$(DC) logs -f

%-log:
	$(DC) logs $*

%-logf:
	$(DC) logs -f $*

# Different to app-log and app-logf, see th_log in
# application_controller.rb and application_record.rb.
# Currently contains account captcha, confirmations and deletions
applog:
	more docker/log/app.log

applogf:
	tail -f docker/log/app.log

dwatch:
	@sudo watch -n1 docker ps -a

status:
	sudo systemctl status thost.service

restart:
	sudo systemctl restart thost.service

stop:
	sudo systemctl stop thost.service

start:
	sudo systemctl start thost.service

patch:
	sudo dnf update --security
	@echo "** Consider if a reboot is needed"

update:
	sudo dnf update
	@echo "** Consider if a reboot is needed"

# Show a log of ssh attempts
ssh-logs:
	 journalctl -q _AUDIT_TYPE=1112 _TRANSPORT=audit | tail -100

# For some reason the thumbnail generator job doesn't timeout like
# it should. These are helpful until I figure out a better plan.
# (Update: Maybe not needed any more.)
showpuppet:
	@ps -eo pid,ppid,etime,cmd | grep /opt/node_modules/puppeteer | grep -v grep | awk '{print $$1, $$2, $$3}'

killpuppet:
	@ps -eo pid,ppid,etime,cmd | grep /opt/node_modules/puppeteer | grep -v grep | awk '{print $$1}' | tac | xargs kill

# Expecting to see some defunct chrome processes left behind by puppeteer.
# They are cleaned up when the delayed job container get restarted.
showchrome:
	@ps -eo pid,ppid,etime,cmd | grep chrome | grep -v grep | grep -v make
