test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

# For testing multiple storage services
test1:
  service: Disk
  root: <%= Rails.root.join("tmp/storage1") %>

test2:
  service: Disk
  root: <%= Rails.root.join("tmp/storage2") %>
  public: true

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

# For testing multiple storage services
local1:
  service: Disk
  root: <%= Rails.root.join("storage1") %>

local2:
  service: Disk
  root: <%= Rails.root.join("storage2") %>
  public: true

<%= Settings.storage_config_yaml(:amazon, :amazon_s3) %>

<%= Settings.storage_config_yaml(:wasabi1, :wasabi_trial_1) %>

<%= Settings.storage_config_yaml(:trial2, :trial_2) %>

<%= Settings.storage_config_yaml(:main, :trial_2) %>

<%= Settings.storage_config_yaml(:thumbs, :thumbs_1) %>

<%= Settings.storage_config_yaml(:thumbs2, :thumbs_2) %>

<%= Settings.storage_config_yaml(:thumbs_public, :thumbs_3) %>

# Use rails credentials:edit to set the AWS secrets (as aws:access_key_id|secret_access_key)
# amazon:
#   service: S3
#   access_key_id: <%= Settings.secrets(:aws, :access_key_id) %>
#   secret_access_key: <%= Settings.secrets(:aws, :secret_access_key) %>
#   region: us-east-1
#   bucket: your_own_bucket

# Remember not to checkin your GCS keyfile to a repository
# google:
#   service: GCS
#   project: your_project
#   credentials: <%= Rails.root.join("path/to/gcs.keyfile") %>
#   bucket: your_own_bucket

# Use rails credentials:edit to set the Azure Storage secret (as azure_storage:storage_access_key)
# microsoft:
#   service: AzureStorage
#   storage_account_name: your_account_name
#   storage_access_key: <%= Settings.secrets(:azure_storage, :storage_access_key) %>
#   container: your_container_name

# mirror:
#   service: Mirror
#   primary: local
#   mirrors: [ amazon, google, microsoft ]
