
- hosts: all
  become: yes
  become_user: root

  vars:
    local_logs_dir: "{{ local_root }}/../logs"
    logs_dir: "{{ home_dir }}/logs-tmp"

  tasks:
  - name: Extract logs
    shell: |
      mkdir -p {{ logs_dir }}
      docker compose logs {{ item }} > {{ logs_dir }}/{{ item }}.log
    with_items:
    - web

  - name: Download logs
    fetch:
      src: "{{ logs_dir }}/{{ item }}.log"
      dest: "{{ local_logs_dir }}/{{ item }}.log"
      flat: yes
    with_items:
    - web
