
- hosts: all
  become: yes
  become_user: root

  tasks:
  - name: Fetch master key
    fetch:
      src: "{{ secrets_dir }}/master.key"
      dest: "{{ master_key_file }}"
      flat: yes

  - name: Fetch credentials file
    fetch:
      src: "{{ secrets_dir }}/credentials.yml.enc"
      dest: "{{ credentials_file }}"
      flat: yes

  - name: Fetch docker pull credentials
    fetch:
      src: "{{ root_home_dir }}/.docker/config.json"
      dest: "{{ docker_config_json }}"
      flat: yes

  - name: Fetch certbot DNS credentials
    fetch:
      src: "{{ home_dir }}/.aws/credentials"
      dest: "{{ certbot_dns_credentials }}"
      flat: yes
