#!/bin/bash
set -euo pipefail

#
# Bash script showing how to use curl to download a private site.
#
# Example usage:
#   ./thost-downloader yoursite youremail@example.com yourpassword
#
# To avoid including your password in scripts, you could do something like
# this for example:
#   echo yourpassword > ~/.thostpass
#   chmod 600 ~/.thostpass
#
# Then:
#   ./thost-downloader yoursite youremail@example.com $(cat ~/.thostpass)
#
# Note that you don't need this for a public site. You can just do:
#   curl -s https://$SITE.tiddlyhost.com/download -o $SITE.html
#

show_usage() {
  echo Usage:
  echo "  $0 <sitename> <email> <password>"
  exit 1
}

SITE=$1
EMAIL=$2
PASSWD=$3

DOWNLOAD_DIR=${DOWNLOAD_DIR:-./downloads}
mkdir -p $DOWNLOAD_DIR

[[ -z "$SITE" ]] && show_usage
[[ -z "$EMAIL" ]] && show_usage
[[ -z "$PASSWD" ]] && show_usage

TIDDLYHOST=tiddlyhost.com
SIGN_IN=https://$TIDDLYHOST/users/sign_in
COOKIES=$(mktemp)
trap "rm -f $COOKIES" EXIT
CURL="curl -s --cookie-jar $COOKIES --cookie $COOKIES"

# Read authenticity_token
TOKEN=$($CURL $SIGN_IN | grep '"csrf-token"' | cut -d'"' -f4)

# Log in
$CURL -X POST $SIGN_IN \
  --data-urlencode "authenticity_token=$TOKEN" \
  --data-urlencode "user[email]=$EMAIL" \
  --data-urlencode "user[password]=$PASSWD" \
  -o /dev/null

# Check we logged in succesfully
OK=$($CURL -I "https://$TIDDLYHOST/sites" | head -1 | grep '200 OK')
[[ -z "$OK" ]] && echo "Login failed." && exit 1

TIMESTAMP=$(date +%Y%m%d%H%M%S)

# Download the site
file="${DOWNLOAD_DIR}/${SITE}.html"
#file="${DOWNLOAD_DIR}/${SITE}.${TIMESTAMP}.html"
echo "Downloading site ${SITE} to ${file}"
$CURL "https://$SITE.tiddlyhost.com/download" -o "$file"

# Clean up
rm -f $COOKIES
