
DC=-sudo docker-compose
DCC=$(DC) exec app bash -c

_help:
	@echo Available tasks:
	@grep '^[^_#\\$$[:space:]][^=/[:space:]]*:' Makefile | cut -d: -f1 | xargs -n1 echo ' make'

shell:
	$(DCC) bash

sandbox:
	$(DCC) 'bin/rails console --sandbox'

console:
	$(DCC) 'bin/rails console'

webshell:
	$(DC) exec web bash

dbshell:
	$(DC) exec db bash

log:
	$(DC) logs

logf:
	$(DC) logs -f

%-log:
	$(DC) logs $*

%-logf:
	$(DC) logs -f $*

dwatch:
	@sudo watch -n1 docker ps -a

status:
	sudo service thost status

restart:
	sudo service thost restart

stop:
	sudo service thost stop

start:
	sudo service thost start

patch:
	sudo dnf update --security
	@echo "** Consider if a reboot is needed"

update:
	sudo dnf update
	@echo "** Consider if a reboot is needed"

#
# For some reason the thumbnail generator job doesn't timeout like
# it should. These are helpful until I figure out a better plan.
#
showpuppet:
	@ps -eo pid,ppid,etime,cmd | grep /opt/node_modules/puppeteer | grep -v grep | awk '{print $$1, $$2, $$3}'

killpuppet:
	@ps -eo pid,ppid,etime,cmd | grep /opt/node_modules/puppeteer | grep -v grep | awk '{print $$1}' | tac | xargs kill

# Expecting to see some defunct chrome processes
showchrome:
	@ps -eo pid,ppid,etime,cmd | grep chrome | grep -v grep | grep -v make
