
DC=-sudo docker-compose
DCC=$(DC) exec app bash -c

_help:
	@echo Available tasks:
	@grep '^[^_#\\$$[:space:]][^=/[:space:]]*:' Makefile | cut -d: -f1 | xargs -n1 echo ' make'

shell:
	$(DCC) bash

sandbox:
	$(DCC) 'bin/rails console --sandbox'

console:
	$(DCC) 'bin/rails console'

webshell:
	$(DC) exec web bash

dbshell:
	$(DC) exec db bash

log:
	$(DC) logs

logf:
	$(DC) logs -f

%-log:
	$(DC) logs $*

%-logf:
	$(DC) logs -f $*

dwatch:
	@sudo watch -n1 docker ps -a

status:
	sudo service thost status

restart:
	sudo service thost restart

stop:
	sudo service thost stop

start:
	sudo service thost start

patch:
	sudo dnf update --security
	@echo "** Consider if a reboot is needed"

update:
	sudo dnf update
	@echo "** Consider if a reboot is needed"

showdupes:
	$(DCC) 'bin/rails runner fixup-scripts/clean-attachment-dupes.rb'

cleandupes:
	$(DCC) 'env REALLY=1 bin/rails runner fixup-scripts/clean-attachment-dupes.rb'
