all:
  hosts:
    prod:
      primary_host: tiddlyhost.com
      tiddlyspot_host: tiddlyspot.com
      ansible_host: "{{ primary_host }}"

      # Todo: Should create this user rather than assume it exists and has sudo
      ansible_user: fedora
      ansible_python_interpreter: /usr/bin/python3.14

      # For letsencrypt
      cert_hosts:
      - "{{ primary_host }}"
      - "{{ tiddlyspot_host }}"

  vars:
    local_root: ../..

    root_home_dir: /root
    home_dir: /home/{{ ansible_user }}

    bin_dir: "{{ home_dir }}/bin"
    bash_rc_dir: "{{ home_dir }}/.bashrc.d"
    docker_dir: "{{ home_dir }}/docker"
    backups_dir: "{{ home_dir }}/backups"
    db_dump_file: "{{ backups_dir }}/dbdump.gz"

    # S3 backup configuration
    s3_backup_enabled: true
    s3_backup_bucket: "tiddlyhost-backups"
    s3_backup_retention_days: 90

    prerelease_empty: https://tiddlywiki.com/prerelease/empty.html

    certbot_dns_credentials: "{{ local_root }}/etc/credentials/aws/certbot-dns-user.yml"
    docker_config_json: "{{ local_root }}/etc/credentials/docker/config-pull.json"
    docker_compose_file: "{{ local_root }}/docker-compose-prod.yml"
    master_key_file: "{{ local_root }}/rails/config/master.key"
    credentials_file: "{{ local_root }}/rails/config/credentials.yml.enc"

    certbot_dir_config: "{{ docker_dir }}/letsencrypt"
    certbot_dir_work: "{{ home_dir }}/.certbot/work"
    certbot_dir_logs: "{{ home_dir }}/.certbot/logs"
    certbot_dir_live: "{{ certbot_dir_config }}/live/{{ primary_host }}"
    certbot_notification_email: simon.baird@gmail.com

    thost_log_dir: "{{ docker_dir }}/log"
    nginx_conf_dir: "{{ docker_dir }}/nginx-conf"
    nginx_html_dir: "{{ docker_dir }}/nginx-html"
    nginx_domains_dir: "{{ docker_dir }}/nginx-domains"
    acme_challenge_dir: "{{ docker_dir }}/acme-challenge"
    rails_conf_dir: "{{ docker_dir }}/config"
    secrets_dir: "{{ docker_dir }}/secrets"

    service_name: thost
    db_name: app_production
    db_user: postgres
