source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '~> 3.4.0'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 7.2.0'
# Use postgresql as the database for Active Record
gem 'pg', '~> 1.1'
# Use Puma as the app server
gem 'puma', '~> 7.0'
# Use SCSS for stylesheets
gem 'sass-rails', '>= 6'
# Transpile app-like JavaScript. Read more: https://github.com/rails/webpacker
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.7'
# Use Active Model has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Might become a rails dependency soon?
# (Removed from stdlib starting Ruby 3.5)
gem 'logger'

# Used in lib/settings
# (Removed from stdlib starting Ruby 3.5)
gem 'ostruct'

# Background jobs
gem 'daemons'
gem 'delayed_job_active_record'

# https://github.com/ambethia/recaptcha
gem 'recaptcha'

# Markdown
gem 'redcarpet', '~> 3.6'

# Use Active Storage variant
# gem 'image_processing', '~> 1.2'

# For memcached
gem 'dalli'

# Pin connection_pool to avoid breaking changes in 3.x related to
# dalli and MemCacheStore
# See: https://github.com/mperham/connection_pool/issues/210
gem 'connection_pool', '< 3.0'

# Added manually to fix error running tests...?
gem 'rexml'

# Use devise for user management and authentication
gem 'devise'

# For captcha and strong passwords
gem 'devise-security'

# Pagination
gem 'will_paginate'

# Used in TspotSite for redirect url
gem 'validate_url'

# https://github.com/mbleigh/acts-as-taggable-on
gem 'acts-as-taggable-on', '~> 13.0'

# https://github.com/smartinez87/exception_notification
gem 'exception_notification'

# For download all button
gem 'rubyzip'

# Why not...
gem 'haml-rails'

# Support S3 for ActiveStorage
gem 'aws-sdk-s3', require: false

# For nice emails
gem 'bootstrap-email'

# For thumbnails and screenshots
gem 'grover'

# For adjective-noun generated site names
gem 'spicy-proton'

# For payments
gem 'pay', '~> 11.4.0'
gem 'stripe', '~> 18.1.0'

# Needed after ruby 3.1 upgrade
gem 'net-imap', require: false
gem 'net-pop', require: false
gem 'net-smtp', require: false

gem 'charlock_holmes'

# Used in app/controllers/admin_controller
gem 'csv', require: false

# https://github.com/Shopify/bootsnap
gem 'bootsnap', require: false

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :windows]

  # https://brakemanscanner.org/
  gem 'brakeman', require: false
end

group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'web-console', '>= 4.1.0'

  # Display performance information such as SQL time and flame graphs for each request in your browser.
  # Can be configured to work on production as well see: https://github.com/MiniProfiler/rack-mini-profiler/blob/master/README.md
  ## It injects javascript so it's not good for TiddlyWikis
  ## TODO: Figure out how to disable it for the tiddlywiki_controller only.
  #gem 'rack-mini-profiler', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  #gem 'spring'

  # Delint some haml
  gem 'haml_lint', require: false
end

group :test do
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '>= 3.26'
  gem 'selenium-webdriver', '~> 4.2'

  # Keep minitest below 6.0.0 to avoid some breaking changes
  # Remove after Rails 8 upgrade (?)
  gem 'minitest', '~> 5.25'

  gem 'mocha', require: false
  gem 'simplecov', require: false
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:windows, :jruby]

gem "jsbundling-rails", "~> 1.3"
